# Generated by Django 5.2.1 on 2025-05-30 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_menu_category_menu_description_menu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.staff'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Tandoor', 'Tandoor'), ('Chinese', 'Chinese'), ('Desserts', 'Desserts'), ('Snacks', 'Snacks'), ('Salads', 'Salads'), ('Soups', 'Soups'), ('MainCourse', 'Main Course'), ('Sides', 'Sides'), ('Breakfast', 'Breakfast'), ('Specials', 'Specials')], max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='orderitem',
        ),
    ]
