# Generated by Django 5.2.1 on 2025-05-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_rename_date_order_order_date_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Tandoor', 'Tandoor'), ('Chinese', 'Chinese'), ('Desserts', 'Desserts'), ('Snacks', 'Snacks'), ('Salads', 'Salads'), ('Soups', 'Soups'), ('MainCourse', 'Main Course'), ('Sides', 'Sides'), ('Breakfast', 'Breakfast'), ('Specials', 'Specials')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
