# Generated by Django 5.2.1 on 2025-05-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_alter_menu_category_alter_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, choices=[('Beverages', 'Beverages'), ('Tandoor', 'Tandoor'), ('Chinese', 'Chinese'), ('Desserts', 'Desserts'), ('Snacks', 'Snacks'), ('Salads', 'Salads'), ('Soups', 'Soups'), ('MainCourse', 'Main Course'), ('Sides', 'Sides'), ('Breakfast', 'Breakfast'), ('Specials', 'Specials')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.staff'),
        ),
    ]
