# Generated by Django 5.2.1 on 2025-05-30 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_alter_menu_category_alter_order_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='App1.staff'),
            preserve_default=False,
        ),
    ]
