# Generated by Django 5.2.1 on 2025-05-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_alter_menu_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customers',
        ),
    ]
