# Generated by Django 5.2.1 on 2025-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_alter_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, choices=[('Beverages', 'Beverages'), ('Tandoor', 'Tandoor'), ('Chinese', 'Chinese'), ('Desserts', 'Desserts'), ('Snacks', 'Snacks'), ('Salads', 'Salads'), ('Soups', 'Soups'), ('MainCourse', 'Main Course'), ('Sides', 'Sides'), ('Breakfast', 'Breakfast'), ('Specials', 'Specials')], default='Specials', max_length=100, null=True),
        ),
    ]
