# Generated by Django 5.2.1 on 2025-05-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_alter_menu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
