# Generated by Django 5.2.1 on 2025-05-30 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_remove_order_customers_remove_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='salary',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='App1.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
