# Generated by Django 5.2.1 on 2025-05-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_customers_customer_rename_orders_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
    ]
