# Generated by Django 5.2.1 on 2025-05-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_remove_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
    ]
