# Generated by Django 5.2.1 on 2025-05-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
