# Generated by Django 5.2.1 on 2025-05-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0018_remove_menu_image_remove_staff_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
