# Generated by Django 5.2.1 on 2025-05-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0019_alter_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, choices=[('Beverages', 'Beverages'), ('Tandoor', 'Tandoor'), ('Chinese', 'Chinese'), ('Desserts', 'Desserts'), ('Snacks', 'Snacks'), ('Salads', 'Salads'), ('Soups', 'Soups'), ('Main Course', 'Main Course'), ('Sides', 'Sides'), ('Breakfast', 'Breakfast'), ('Specials', 'Specials')], max_length=50, null=True),
        ),
    ]
